# Generated by Django 3.2.9 on 2021-12-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs50game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs50gpost',
            name='blurb',
            field=models.TextField(default='A paragraph that encapsulates what this blog post is about. It can be much longer than a subtitle for example.'),
            preserve_default=False,
        ),
    ]
