# Generated by Django 3.2.9 on 2021-12-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs50game', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs50gpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cs50gpost',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cs50gpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
