# Generated by Django 3.2.9 on 2021-12-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs50game', '0005_auto_20211218_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cs50gpost',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='cs50game.Category'),
        ),
    ]
