# Generated by Django 3.2.9 on 2021-12-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs50game', '0006_auto_20211219_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cs50gpost',
            name='blurb',
        ),
    ]
