# Generated by Django 3.2.9 on 2021-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coverpic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
